name: GithubCICD Direct Debug

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  
jobs:
  build:

    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache ARM GCC Toolchain
      uses: actions/cache@v4
      with:
      cmakePreset: 'ci-build-preset' # Refers to a preset defined in CMakePresets.json
        #path: C:\arm-gcc\
        #key: arm-gcc-14.2-rel1 # If updating to new version, update this key to pull in new version
   