name: GithubCICD Direct Debug

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
     - name: Configure and Build
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'Debug' # Refers to a preset defined in CMakePresets.json