name: GithubCICD Direct Debug

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  
jobs:
  build:

    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache ARM GCC Toolchain
      id: cache-arm-gcc
      uses: actions/cache@v4
      with:
        path: C:\arm-gcc\
        key: arm-gcc-14.2-rel1 # If updating to new version, update this key to pull in new version
        
    - name: Download ARM GCC Toolchain (14.2.Rel1) # If update to new version, update cache key
      if: steps.cache-arm-gcc.outputs.cache-hit != 'true'
      run: |
        curl -LO https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-mingw-w64-x86_64-arm-none-eabi.zip
        7z x arm-gnu-toolchain-14.2.rel1-mingw-w64-x86_64-arm-none-eabi.zip -oC:\arm-gcc

    - name: Add GCC to PATH
      run: echo "C:\arm-gcc\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
      

    - name: Cache GoogleTest
      id: cache-gtest
      uses: actions/cache@v4
      with:
        echo ${{ github.workspace }}
        path: ${{ github.workspace }}\VScodeGithubActLearning\Tests\googletest-src
        key: gtest-cache-1.14.0

    - name: Download GTest (1.14.0) # If update to new version, update cache key
      if: steps.cache-gtest.outputs.cache-hit != 'true'
      run: |
        curl -LO https://github.com/google/googletest/archive/refs/tags/v1.14.0.zip
        7z x v1.14.0.zip -o${{ github.workspace }}\VScodeGithubActLearning\Tests\
        Rename-Item -Path "${{ github.workspace }}\VScodeGithubActLearning\Tests\googletest-1.14.0" -NewName "googletest-src"

    - name: Configure CMake for Unit Tests
      run: >
        cmake -G "MinGW Makefiles"
        -DBUILD_FIRMWARE=OFF
        -DBUILD_TESTS=ON
        -S "${{ github.workspace }}\VScodeGithubActLearning\Tests"
        -B "${{ github.workspace }}\VScodeGithubActLearning\Tests\build-tests"
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}      