name: GithubCICD Direct Debug

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  
jobs:
  build_and_test:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
    
     - name: Configure and Build
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'Debug' # Refers to a preset defined in CMakePresets.json